// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace KVwWPF.Models
{
    public partial class Kunde
    {
        public Kunde()
        {
            Rechnung = new HashSet<Rechnung>();
        }

        public int KundePk { get; set; }
        public int Kundenummer { get; set; }
        public string KundeVorname { get; set; }
        public string KundeNachname { get; set; }
        public string KundeAdresse { get; set; }
        public string KundeEmail { get; set; }
        public string KundeTelNr { get; set; }
        public string Passwort { get; set; }

        public virtual ICollection<Rechnung> Rechnung { get; set; }
    }
}