// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace KVwWPF.Models
{
    public partial class Mitarbeiter
    {
        public int MaPk { get; set; }
        public string MaVorname { get; set; }
        public string MaNachname { get; set; }
        public string MaPasswort { get; set; }
    }
}