// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace KVwWPF.Models
{
    public partial class Rechnung
    {
        public Rechnung()
        {
            ProdRechZuordnung = new HashSet<ProdRechZuordnung>();
        }

        public int RechnungPk { get; set; }
        public int RechNr { get; set; }
        public DateTime RechDat { get; set; }
        public double RechSum { get; set; }
        public int RechKundeFk { get; set; }

        public virtual Kunde RechKundeFkNavigation { get; set; }
        public virtual ICollection<ProdRechZuordnung> ProdRechZuordnung { get; set; }
    }
}